### ISSUE TITLE
Update TeamSpeak logo

### ISSUE THREAD

**Issue by D0mm4S** [2factorauth/twofactorauth#4519]
Here is the logo according to your guidelines.
![TeamSpeak logo unedited](https://user-images.githubusercontent.com/12242391/72212001-316b1080-34d5-11ea-9e9a-955fbd9b6eb7.png)
Answer from TS to implement 2FA in short: planned.

**Comment by Carlgo11** [comment]
Danke!

**Comment by Stevoisiak** [comment]
This was resolved by #4313. Can a member close this?

**Comment by D0mm4S** [comment]
I still see the old one even after clearing cache or is the live site different from this here?

**Comment by Stevoisiak** [comment]
Huh. The icon was updated in master [16 days ago](https://github.com/phallobst/twofactorauth/blob/463e98237cd0dbf4d300652eb5aab87b0c265ca5/img/communication/teamspeak.png), but it doesn't seem to have updated on the live site yet.

**Comment by D0mm4S** [comment]
> Huh. The icon was updated in master [16 days ago](https://github.com/phallobst/twofactorauth/blob/463e98237cd0dbf4d300652eb5aab87b0c265ca5/img/communication/teamspeak.png), but it doesn't seem to have updated on the live site yet.

Exactly :) I still closed this issue since it is merged.

**Comment by Carlgo11** [comment]
@D0mm4S @Stevoisiak loads fine for me. Check your cache again?

**Comment by D0mm4S** [comment]
@Carlgo11 Cleared Cache, used private tab, even phone (never opened the site there). Still old logo.

**Comment by Carlgo11** [comment]
![image](https://user-images.githubusercontent.com/3535780/73710357-0787c100-4704-11ea-8da0-2a98bb3a29e8.jpg)

**Comment by D0mm4S** [comment]
It shows for me now too. :) Took a while.
